---
name: Deploy

concurrency:
  group: "deploy-infrastructure"
  cancel-in-progress: false

on:
  push:
    branches: [main]

jobs:
  deploy-infrastructure:
    name: Deploy
    runs-on: ubuntu-latest
    environment: gcp-project
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup just
        uses: extractions/setup-just@v1

      - name: Utilize .terraform cache
        uses: actions/cache@v2
        with:
          path: terraform/.terraform
          key: ${{ hashFiles('terraform/.terraform.lock.hcl') }}

      - name: Read .terraform-version
        id: read_tf_version
        run: just set-tf-ver-output

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ steps.read_tf_version.outputs.terraform_version }}

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/567739286055/locations/global/workloadIdentityPools/los-verdes-digital-membership/providers/los-verdes-digital-membership"
          service_account: "gh-terraform-applier@lv-digital-membership.iam.gserviceaccount.com"

      - name: Deploy
        run: just deploy
        env:
          TF_VAR_squarespace_api_key: ${{ secrets.cloudflare_api_token }}
          TF_VAR_oauth_client_id: ${{ secrets.oauth_client_id }}
          TF_VAR_oauth_client_secret: ${{ secrets.oauth_client_secret }}
          TF_VAR_apple_pass_certificate: ${{ secrets.apple_pass_certificate }}
          TF_VAR_apple_pass_private_key_password: ${{ secrets.apple_pass_private_key_password }}
