name: Deploy Infrastructure

concurrency:
  group: "deploy-infrastructure"
  cancel-in-progress: false

on:
  push:
    branches: [main]

jobs:
  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    environment: gcp-project
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup just
        uses: extractions/setup-just@v1

      - name: Utilize .terraform cache
        uses: actions/cache@v2
        with:
          path: terraform/.terraform
          key: ${{ hashFiles('terraform/.terraform.lock.hcl') }}

      - name: Read .terraform-version
        id: read_tf_version
        run: just set-tf-ver-output

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ steps.read_tf_version.outputs.terraform_version }}

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/567739286055/locations/global/workloadIdentityPools/jeffwecan-digital-membership/providers/jeffwecan-digital-membership"
          service_account: "gh-terraform-applier@lv-digital-membership.iam.gserviceaccount.com"

      - name: Apply - terraform
        run: just tf-auto-apply
        env:
          TF_VAR_github_repo: ${{ github.repository }}
          TF_VAR_cloudflare_api_token: ${{ secrets.cloudflare_api_token }}
          TF_VAR_site_publisher_gh_app_key: ${{ secrets.site_publisher_gh_app_key }}
