name: Build and Publish Images to GCR

on:
  push:
    branches: [main, cd_workflow_updates]
  # workflow_call:
  #   inputs:
  #     image_tag:
  #       description: "The image name suffix to set on our published container image. Defaults to to `sha_<current git ref>`"
  #       type: string
  #       required: false
  #       default: sha_${{ github.sha }}
  # workflow_dispatch:
  #   inputs:
  #     image_tag:
  #       description: "The image name suffix to set on our published container image."
  #       type: string
  #       required: true

concurrency:
  group: build-and-publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-publish:
    name: "Build and Publish Images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - worker
          - website
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        id: auth
        with:
          workload_identity_provider: "projects/567739286055/locations/global/workloadIdentityPools/los-verdes-digital-membership/providers/los-verdes-digital-membership"
          service_account: "github-deployer@lv-digital-membership.iam.gserviceaccount.com"
          access_token_scopes: "https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/devstorage.read_write"
          token_format: access_token

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Generate Docker Tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            "${{ vars.CONTAINER_IMAGE_REPO }}/${{ matrix.service }}"
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and Push to GCR
        id: publish
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          target: ${{ matrix.service }}
          # Using native GitHub action caching as shown here:
          # https://github.com/docker/build-push-action/issues/252#issuecomment-889339470
          cache-from: type=gha,scope=$${{ github.workflow }}
          cache-to: type=gha,scope=$${{ github.workflow }},mode=max
