---
name: Lint and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint Configuration"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Super Linter
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_ALL_CODEBASE: false
          # JSCPD - meebee later...
          # VALIDATE_JSCPD_ALL_CODEBASE: true
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_CSS: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_PYTHON_ISORT: false
          # TODO: toggle GITHUB_ACTIONS back on after one, or both, of these issues are resolved:
          # https://github.com/github/super-linter/issues/1852
          # https://github.com/rhysd/actionlint/issues/91
          VALIDATE_GITHUB_ACTIONS: false

  test:
    name: "Run Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup just
        uses: extractions/setup-just@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Utilize pip cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install pytest
        run: pip install pytest

      - name: Run Tests
        run: |
          python -m pytest \
            --durations=10 \
            --junitxml=artifacts/junit.xml
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
          # PYTEST_RUN_PATH: tests
